import java_cup.runtime.*;
import ast.*;
import java.util.*;


/*  Código del Parser  */
parser code {:
    private int syntaxErrors = 0;

    public int getSyntaxErrors() {
        return syntaxErrors;
    }

    @Override
    public void syntax_error(Symbol cur_token) {
        syntaxErrors++;

        int line = cur_token.left + 1;
        int col  = cur_token.right + 1;

        System.err.println("Error sintáctico en línea " + line + ", columna " + col);
        System.err.println("Token no esperado: " + sym.terminalNames[cur_token.sym] +
            (cur_token.value != null ? " (" + cur_token.value + ")" : ""));
    }

    @Override
    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        System.err.println("Error fatal: No se pudo recuperar del error sintáctico.");
    }
:};

/*  Declaraciones de Terminales  */
terminal WORLD, LOCAL, ENDL;
terminal PLUS, MINUS, TIMES, DIV, IDIV, MOD, POW, INC, DEC;
terminal LT, LE, GT, GE, EQ, NE;
terminal AND, OR, NOT;
terminal DECIDE, OF, ELSE, END;
terminal LOOP, EXIT, WHEN, FOR;
terminal RETURN, BREAK;
terminal SHOW, GET;
terminal GIFT, NAVIDAD, COAL;

/* Tipos */
terminal INT, FLOAT, CHAR, STRING, BOOLEAN, VOID; 
terminal COMMA, LBRACKET, RBRACKET, ASSIGN;

terminal LPAR, RPAR;      /* ¿ y ? */
terminal LBRACE, RBRACE;  /* ¡ y ! */
terminal ARROW;           /* -> */

terminal String IDENT;
terminal Object INT_LIT;
terminal Object FLOAT_LIT;
terminal Object BOOL_LIT;
terminal String STRING_LIT;
terminal String CHAR_LIT;
terminal ERROR, UMINUS;

/*  No terminales  */
non terminal ProgramNode program;
non terminal List<ASTNode> top_elements;
non terminal ASTNode top_element;
non terminal ASTNode decl_global;
non terminal MainNode main_nav;
non terminal BlockNode bloque;
non terminal List<ASTNode> sentencias, sentencia_list;
non terminal ASTNode sentencia;
non terminal List<ParamNode> params, lista_params;
non terminal ParamNode param;
non terminal ASTNode expr, literal, io, decl, assignment, for_step;
non terminal ASTNode decide_stmt;
non terminal LoopNode loop_stmt;
non terminal ForNode for_stmt;
non terminal List<ASTNode> casos;
non terminal ASTNode cason, else_opt;
non terminal List<ASTNode> funciones_list;
non terminal FunctionNode funcion;
non terminal CallNode llamada;
non terminal List<ASTNode> lista_expr, lista_init;
non terminal String tipo;
non terminal ASTNode lvalue;
non terminal ASTNode expr_arg;
non terminal ASTNode init_elem;
non terminal Object endl_opt;

/*  Precedencia y Asociatividad  */
precedence right ASSIGN, ARROW;
precedence left OR;
precedence left AND;
precedence right NOT;
precedence left LT, LE, GT, GE, EQ, NE;
precedence left PLUS, MINUS;
precedence left TIMES, DIV, IDIV, MOD;
precedence right POW;
precedence right INC, DEC, UMINUS;
precedence left LPAR;


start with program;

/*  Producciones  */
program ::= top_elements:el
          {:
             List<ASTNode> decls = new ArrayList<>();
             List<ASTNode> funcs = new ArrayList<>();
             List<MainNode> mains = new ArrayList<>();

             for (ASTNode n : el) {
                 if (n instanceof DeclNode) decls.add(n);
                 else if (n instanceof FunctionNode) funcs.add(n);
                 else if (n instanceof MainNode) mains.add((MainNode)n);
             }
             RESULT = new ProgramNode(decls, funcs, mains, elleft, elright); 
          :}
          ;

top_elements ::= top_element:e
               {: List<ASTNode> l = new ArrayList<>(); if(e != null) l.add(e); RESULT = l; :}
             | top_elements:l top_element:e
               {: if(e != null) l.add(e); RESULT = l; :}
             ;

top_element ::= decl_global:d {: RESULT = d; :}
              | funcion:f     {: RESULT = f; :}
              | main_nav:m    {: RESULT = m; :}
              ;

tipo ::= INT:i      {: RESULT = "int"; :}
       | FLOAT:f    {: RESULT = "float"; :}
       | CHAR:c     {: RESULT = "char"; :}
       | BOOLEAN:b  {: RESULT = "boolean"; :}
       | STRING:s   {: RESULT = "string"; :}
       | VOID:v     {: RESULT = "void"; :}
       ;

decl_global ::= WORLD tipo:t IDENT:id ENDL
                {: RESULT = new DeclNode(id, null, true, t, new ArrayList<>(), idleft, idright); :}
              | WORLD tipo:t IDENT:id ASSIGN expr:e ENDL
                {: RESULT = new DeclNode(id, e, true, t, new ArrayList<>(), idleft, idright); :}
              /* Soporte arreglos globales */
              | WORLD tipo:t IDENT:id LBRACKET INT_LIT:sz1 RBRACKET ENDL
                {: 
                   List<Integer> dims = new ArrayList<>(); 
                   dims.add(Integer.parseInt(sz1.toString())); 
                   RESULT = new DeclNode(id, null, true, t, dims, idleft, idright); 
                :}
              | WORLD tipo:t IDENT:id LBRACKET INT_LIT:sz1 RBRACKET ASSIGN LBRACE lista_init:l RBRACE ENDL
                {: 
                   List<Integer> dims = new ArrayList<>(); 
                   dims.add(Integer.parseInt(sz1.toString())); 
                   RESULT = new DeclNode(id, new ArrayLiteralNode(l, lleft, lright), true, t, dims, idleft, idright); 
                :}
              | WORLD tipo:t IDENT:id LBRACKET INT_LIT:sz1 RBRACKET LBRACKET INT_LIT:sz2 RBRACKET ENDL
                {: 
                   List<Integer> dims = new ArrayList<>(); 
                   dims.add(Integer.parseInt(sz1.toString())); 
                   dims.add(Integer.parseInt(sz2.toString()));
                   RESULT = new DeclNode(id, null, true, t, dims, idleft, idright); 
                :}
              | WORLD tipo:t IDENT:id LBRACKET INT_LIT:sz1 RBRACKET LBRACKET INT_LIT:sz2 RBRACKET ASSIGN LBRACE lista_init:l RBRACE ENDL
                {: 
                   List<Integer> dims = new ArrayList<>(); 
                   dims.add(Integer.parseInt(sz1.toString())); 
                   dims.add(Integer.parseInt(sz2.toString()));
                   RESULT = new DeclNode(id, new ArrayLiteralNode(l, lleft, lright), true, t, dims, idleft, idright); 
                :}
              ;

funcion ::= GIFT tipo:t IDENT:id params:p bloque:b
            {: RESULT = new FunctionNode(id, t, p, b, idleft, idright); :}
          ;

main_nav ::= NAVIDAD:n params:p bloque:b
         {: RESULT = new MainNode(b, false, p, nleft, nright); :}
       | COAL NAVIDAD:n params:p bloque:b
         {: RESULT = new MainNode(b, true, p, nleft, nright); :}
       ;

params ::= LPAR RPAR
           {: RESULT = new ArrayList<ParamNode>(); :}
         | LPAR lista_params:l RPAR
           {: RESULT = l; :}
         ;

lista_params ::= param:p
                 {: List<ParamNode> l = new ArrayList<ParamNode>(); l.add(p); RESULT = l; :}
               | lista_params:l COMMA param:p
                 {: l.add(p); RESULT = l; :}
               ;

param ::= tipo:t IDENT:id
          {: RESULT = new ParamNode(id, t, idleft, idright); :}
        ;

bloque ::= LBRACE sentencias:s RBRACE
           {: RESULT = new BlockNode(s, sleft, sright); :}
         ;

sentencias ::= /* empty */
               {: RESULT = new ArrayList<ASTNode>(); :}
             | sentencia_list:sl
               {: RESULT = sl; :}
             ;

sentencia_list ::= sentencia:s
                   {: List<ASTNode> sl = new ArrayList<ASTNode>(); sl.add(s); RESULT = sl; :}
                 | sentencia_list:sl sentencia:s
                   {: if(s != null) sl.add(s); RESULT = sl; :}
                 ;

sentencia ::= io:i {: RESULT = i; :}
             | decl:d {: RESULT = d; :}
             | decide_stmt:ds {: RESULT = ds; :}
             | loop_stmt:ls {: RESULT = ls; :}
             | for_stmt:fs {: RESULT = fs; :}
             | BREAK:b ENDL {: RESULT = new BreakNode(bleft, bright); :}
             | RETURN:r ENDL {: RESULT = new ReturnNode(null, rleft, rright); :}
             | RETURN:r expr:e ENDL {: RESULT = new ReturnNode(e, rleft, rright); :}
             | assignment:a ENDL {: RESULT = a; :}
             | expr:e ENDL {: RESULT = e; :}
             | error ENDL {: RESULT = null; :}
             ;

/* decl rules continue here */

decl ::= LOCAL tipo:t IDENT:id ENDL
         {: RESULT = new DeclNode(id, null, false, t, new ArrayList<>(), idleft, idright); :}
       | LOCAL tipo:t IDENT:id ASSIGN expr:e ENDL
         {: RESULT = new DeclNode(id, e, false, t, new ArrayList<>(), idleft, idright); :}
       /* Soporte arreglos */
       | LOCAL tipo:t IDENT:id LBRACKET INT_LIT:sz1 RBRACKET ENDL
         {: 
            List<Integer> dims = new ArrayList<>(); 
            dims.add(Integer.parseInt(sz1.toString())); 
            RESULT = new DeclNode(id, null, false, t, dims, idleft, idright); 
         :}
       | LOCAL tipo:t IDENT:id LBRACKET INT_LIT:sz1 RBRACKET ASSIGN LBRACE lista_init:l RBRACE ENDL
         {:
            List<Integer> dims = new ArrayList<>();
            dims.add(Integer.parseInt(sz1.toString()));
            RESULT = new DeclNode(id, new ArrayLiteralNode(l, lleft, lright), false, t, dims, idleft, idright);
         :}
       | LOCAL tipo:t IDENT:id LBRACKET INT_LIT:sz1 RBRACKET LBRACKET INT_LIT:sz2 RBRACKET ENDL
         {: 
            List<Integer> dims = new ArrayList<>(); 
            dims.add(Integer.parseInt(sz1.toString())); 
            dims.add(Integer.parseInt(sz2.toString()));
            RESULT = new DeclNode(id, null, false, t, dims, idleft, idright); 
         :}
       | LOCAL tipo:t IDENT:id LBRACKET INT_LIT:sz1 RBRACKET LBRACKET INT_LIT:sz2 RBRACKET ASSIGN LBRACE lista_init:l RBRACE ENDL
         {:
            List<Integer> dims = new ArrayList<>();
            dims.add(Integer.parseInt(sz1.toString()));
            dims.add(Integer.parseInt(sz2.toString()));
            RESULT = new DeclNode(id, new ArrayLiteralNode(l, lleft, lright), false, t, dims, idleft, idright);
         :}


       /* Para for */
       | tipo:t IDENT:id ASSIGN expr:e
         {: RESULT = new DeclNode(id, e, false, t, new ArrayList<>(), idleft, idright); :}
       ;

decide_stmt ::= DECIDE:d OF casos:c else_opt:el END DECIDE ENDL
                {: RESULT = new DecideNode(null, c, el, dleft, dright); :}
              | DECIDE:d OF casos:c else_opt:el END DECIDE
                {: RESULT = new DecideNode(null, c, el, dleft, dright); :}
              ;

casos ::= cason:c
          {: List<ASTNode> cl = new ArrayList<>(); cl.add(c); RESULT = cl; :}
        | casos:cl cason:c
          {: cl.add(c); RESULT = cl; :}
        ;

cason ::= expr:e ARROW bloque:b
          {: RESULT = new CaseNode(e, b, eleft, eright); :}
        ;

else_opt ::= /* empty */
             {: RESULT = null; :}
           | ELSE ARROW bloque:b
             {: RESULT = b; :}
           ;

loop_stmt ::= LOOP:l sentencias:s EXIT WHEN expr:e ENDL END LOOP ENDL
              {: RESULT = new LoopNode(new BlockNode(s, sleft, sright), e, lleft, lright); :}
            | LOOP:l sentencias:s EXIT WHEN expr:e ENDL END LOOP
              {: RESULT = new LoopNode(new BlockNode(s, sleft, sright), e, lleft, lright); :}
            ;

for_stmt ::= FOR:f LPAR decl:d endl_opt expr:cond endl_opt for_step:step RPAR bloque:b
             {: RESULT = new ForNode(d, cond, step, b, fleft, fright); :}
           ;

assignment ::= lvalue:l ASSIGN expr:e
               {: RESULT = new AssignNode(l, e, lleft, lright); :}
             ;

for_step ::= assignment:a {: RESULT = a; :}
           | expr:e {: RESULT = e; :}
           | /* empty */
           ;

endl_opt ::= ENDL
           | /* empty */
           ;

io ::= SHOW:s expr:e ENDL
       {: RESULT = new ShowNode(e, sleft, sright); :}
     | GET:g lvalue:lv ENDL
       {: RESULT = new GetNode(lv, gleft, gright); :}
     ;

lvalue ::= IDENT:id
           {: RESULT = new VariableNode(id, idleft, idright); :}
         | IDENT:id LBRACKET expr:i1 RBRACKET
           {:
              List<ASTNode> idx = new ArrayList<>();
              idx.add(i1);
              RESULT = new ArrayAccessNode(new VariableNode(id, idleft, idright), idx, idleft, idright);
           :}
         | IDENT:id LBRACKET expr:i1 RBRACKET LBRACKET expr:i2 RBRACKET
           {:
              List<ASTNode> idx = new ArrayList<>();
              idx.add(i1); idx.add(i2);
              RESULT = new ArrayAccessNode(new VariableNode(id, idleft, idright), idx, idleft, idright);
           :}
         ;


expr ::= lvalue:lv {: RESULT = lv; :}
       | literal:l {: RESULT = l; :}
       | expr:e1 PLUS  expr:e2 {: RESULT = new BinaryNode(e1, "+", e2, e1left, e1right); :}
       | expr:e1 MINUS expr:e2 {: RESULT = new BinaryNode(e1, "-", e2, e1left, e1right); :}
       | expr:e1 TIMES expr:e2 {: RESULT = new BinaryNode(e1, "*", e2, e1left, e1right); :}
       | expr:e1 DIV   expr:e2 {: RESULT = new BinaryNode(e1, "/", e2, e1left, e1right); :}
       | expr:e1 IDIV  expr:e2 {: RESULT = new BinaryNode(e1, "//", e2, e1left, e1right); :}
       | expr:e1 MOD   expr:e2 {: RESULT = new BinaryNode(e1, "%", e2, e1left, e1right); :}
       | expr:e1 POW   expr:e2 {: RESULT = new BinaryNode(e1, "^", e2, e1left, e1right); :}
       | MINUS:m expr:e {: RESULT = new UnaryNode("-", e, true, mleft, mright); :} %prec UMINUS
       | INC:i lvalue:lv {: RESULT = new UnaryNode("++", lv, true, ileft, iright); :}
       | DEC:d lvalue:lv {: RESULT = new UnaryNode("--", lv, true, dleft, dright); :}
       | lvalue:lv INC:i {: RESULT = new UnaryNode("++", lv, false, lvleft, lvright); :}
       | lvalue:lv DEC:d {: RESULT = new UnaryNode("--", lv, false, lvleft, lvright); :}
       | expr:e1 LT expr:e2 {: RESULT = new BinaryNode(e1, "<", e2, e1left, e1right); :}
       | expr:e1 LE expr:e2 {: RESULT = new BinaryNode(e1, "<=", e2, e1left, e1right); :}
       | expr:e1 GT expr:e2 {: RESULT = new BinaryNode(e1, ">", e2, e1left, e1right); :}
       | expr:e1 GE expr:e2 {: RESULT = new BinaryNode(e1, ">=", e2, e1left, e1right); :}
       | expr:e1 EQ expr:e2 {: RESULT = new BinaryNode(e1, "==", e2, e1left, e1right); :}
       | expr:e1 NE expr:e2 {: RESULT = new BinaryNode(e1, "!=", e2, e1left, e1right); :}
       | expr:e1 AND expr:e2 {: RESULT = new BinaryNode(e1, "&&", e2, e1left, e1right); :}
       | expr:e1 OR  expr:e2 {: RESULT = new BinaryNode(e1, "||", e2, e1left, e1right); :}
       | NOT:n expr:e {: RESULT = new UnaryNode("!", e, true, nleft, nright); :}
       | LPAR expr:e RPAR {: RESULT = e; :}
       | llamada:ll {: RESULT = ll; :}
       ;



expr_arg ::= lvalue:lv {: RESULT = lv; :}
          | literal:l {: RESULT = l; :}
          | expr_arg:e1 PLUS  expr_arg:e2 {: RESULT = new BinaryNode(e1, "+", e2, e1left, e1right); :}
          | expr_arg:e1 MINUS expr_arg:e2 {: RESULT = new BinaryNode(e1, "-", e2, e1left, e1right); :}
          | expr_arg:e1 TIMES expr_arg:e2 {: RESULT = new BinaryNode(e1, "*", e2, e1left, e1right); :}
          | expr_arg:e1 DIV   expr_arg:e2 {: RESULT = new BinaryNode(e1, "/", e2, e1left, e1right); :}
          | expr_arg:e1 IDIV  expr_arg:e2 {: RESULT = new BinaryNode(e1, "//", e2, e1left, e1right); :}
          | expr_arg:e1 MOD   expr_arg:e2 {: RESULT = new BinaryNode(e1, "%", e2, e1left, e1right); :}
          | expr_arg:e1 POW   expr_arg:e2 {: RESULT = new BinaryNode(e1, "^", e2, e1left, e1right); :}
          | MINUS:m expr_arg:e {: RESULT = new UnaryNode("-", e, true, mleft, mright); :} %prec UMINUS
          | INC:i lvalue:lv {: RESULT = new UnaryNode("++", lv, true, ileft, iright); :}
          | DEC:d lvalue:lv {: RESULT = new UnaryNode("--", lv, true, dleft, dright); :}
          | expr_arg:e1 LT expr_arg:e2 {: RESULT = new BinaryNode(e1, "<", e2, e1left, e1right); :}
          | expr_arg:e1 LE expr_arg:e2 {: RESULT = new BinaryNode(e1, "<=", e2, e1left, e1right); :}
          | expr_arg:e1 GT expr_arg:e2 {: RESULT = new BinaryNode(e1, ">", e2, e1left, e1right); :}
          | expr_arg:e1 GE expr_arg:e2 {: RESULT = new BinaryNode(e1, ">=", e2, e1left, e1right); :}
          | expr_arg:e1 EQ expr_arg:e2 {: RESULT = new BinaryNode(e1, "==", e2, e1left, e1right); :}
          | expr_arg:e1 NE expr_arg:e2 {: RESULT = new BinaryNode(e1, "!=", e2, e1left, e1right); :}
          | expr_arg:e1 AND expr_arg:e2 {: RESULT = new BinaryNode(e1, "&&", e2, e1left, e1right); :}
          | expr_arg:e1 OR  expr_arg:e2 {: RESULT = new BinaryNode(e1, "||", e2, e1left, e1right); :}
          | NOT:n expr_arg:e {: RESULT = new UnaryNode("!", e, true, nleft, nright); :}
          | LPAR expr_arg:e RPAR {: RESULT = e; :}
          | llamada:ll {: RESULT = ll; :}
          ;

llamada ::= IDENT:id LPAR RPAR
            {: RESULT = new CallNode(id, new ArrayList<ASTNode>(), idleft, idright); :}
          | IDENT:id LPAR lista_expr:l RPAR
            {: RESULT = new CallNode(id, l, idleft, idright); :}
          ;

lista_expr ::= expr_arg:e
                {: List<ASTNode> l = new ArrayList<ASTNode>(); l.add(e); RESULT = l; :}
              | lista_expr:l COMMA expr_arg:e
                {: l.add(e); RESULT = l; :}
              ;


lista_init ::= init_elem:e
                {: List<ASTNode> l = new ArrayList<ASTNode>(); l.add(e); RESULT = l; :}
             | lista_init:l COMMA init_elem:e
                {: l.add(e); RESULT = l; :}
             ;


init_elem ::= literal:l
              {: RESULT = l; :}
            | LBRACE lista_init:l RBRACE
              {: RESULT = new ArrayLiteralNode(l, lleft, lright); :}
            ;


literal ::= INT_LIT:n {: RESULT = new LiteralNode(n, "int", nleft, nright); :}
          | FLOAT_LIT:f {: RESULT = new LiteralNode(f, "float", fleft, fright); :}
          | STRING_LIT:s {: RESULT = new LiteralNode(s, "string", sleft, sright); :}
          | BOOL_LIT:b {: RESULT = new LiteralNode(b, "bool", bleft, bright); :}
          | CHAR_LIT:c {: RESULT = new LiteralNode(c, "char", cleft, cright); :}
          ;
