import java_cup.runtime.*;

/* ====== Declaraciones ====== */
terminal WORLD, LOCAL, ENDL;
terminal PLUS, MINUS, TIMES, DIV, IDIV, MOD, POW, INC, DEC;
terminal LT, LE, GT, GE, EQ, NE;
terminal AND, OR, NOT;
terminal DECIDE, OF, ELSE, END;
terminal LOOP, EXIT, WHEN, FOR;
terminal RETURN, BREAK;
terminal SHOW, GET;
terminal GIFT, NAVIDAD, COAL;

terminal LPAR, RPAR;      /* ¿ y ? */
terminal LBRACE, RBRACE;  /* ¡ y ! */
terminal ARROW;           /* -> */

terminal IDENT;
terminal INT_LIT, FLOAT_LIT, BOOL_LIT, CHAR_LIT, STRING_LIT;
terminal ERROR;

/* ====== No terminales ====== */
non terminal program, decl_global, main, bloque, sentencias, sentencia, params;

/* ====== Start ====== */
start with program;

/* ====== Producciones ====== */
program ::= decl_global main
          ;

decl_global ::= WORLD IDENT ENDL
              ;

main ::= NAVIDAD params bloque
       | COAL NAVIDAD params bloque
       ;

params ::= LPAR RPAR
         ;

bloque ::= LBRACE sentencias RBRACE
         ;

sentencias ::= /* empty */
             | sentencias sentencia
             ;

sentencia ::= SHOW ENDL
            | LOCAL IDENT ENDL
            | GET ENDL
            | BREAK ENDL
            | RETURN ENDL
            ;
