
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 6;
  public static final int IDENT = 10;
  public static final int POW = 9;
  public static final int WORLD = 2;
  public static final int MOD = 8;
  public static final int ERROR = 11;
  public static final int LOCAL = 3;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int error = 1;
  public static final int TIMES = 7;
  public static final int ENDL = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "WORLD",
  "LOCAL",
  "ENDL",
  "PLUS",
  "MINUS",
  "TIMES",
  "MOD",
  "POW",
  "IDENT",
  "ERROR"
  };
}

